function out1 = bboShift(lam1,lam2,lam3,theta,phi1,phi2,l,choice)
%BBOSHIFT
%    OUT1 = BBOSHIFT(LAM1,LAM2,LAM3,THETA,PHI1,PHI2,L)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    04-Dec-2019 09:52:24
%    Modified by Randy Lemons 16-Dec-2019

t2 = lam1.^2;
t3 = lam2.^2;
t4 = lam3.^2;
t5 = (theta.*pi)./1.8e+2;
t6 = t4.*1.0e+12;

if choice == 1
    out1 = -phi2-(l.*pi.*sqrt(1.0./(sin(t5).^2./(t4.*-1.516e+10+1.224e-2./(t6-1.667e-2)+2.3753)+cos(t5).^2./(t4.*-1.354e+10+1.878e-2./(t6-1.822e-2)+2.7359))).*2.0)./lam3+(l.*pi.*sqrt(t2.*-1.354e+10+1.878e-2./(t2.*1.0e+12-1.822e-2)+2.7359).*2.0)./lam1+(l.*pi.*sqrt(t3.*-1.354e+10+1.878e-2./(t3.*1.0e+12-1.822e-2)+2.7359).*2.0)./lam2;
elseif choice == 2
    out1 = -phi1-(l.*pi.*sqrt(1.0./(sin(t5).^2./(t4.*-1.516e+10+1.224e-2./(t6-1.667e-2)+2.3753)+cos(t5).^2./(t4.*-1.354e+10+1.878e-2./(t6-1.822e-2)+2.7359))).*2.0)./lam3+(l.*pi.*sqrt(t2.*-1.354e+10+1.878e-2./(t2.*1.0e+12-1.822e-2)+2.7359).*2.0)./lam1+(l.*pi.*sqrt(t3.*-1.354e+10+1.878e-2./(t3.*1.0e+12-1.822e-2)+2.7359).*2.0)./lam2;
elseif choice == 3
    out1 = phi1+phi2-(l.*pi.*sqrt(1.0./(sin(t5).^2./(t4.*-1.516e+10+1.224e-2./(t6-1.667e-2)+2.3753)+cos(t5).^2./(t4.*-1.354e+10+1.878e-2./(t6-1.822e-2)+2.7359))).*2.0)./lam3+(l.*pi.*sqrt(t2.*-1.354e+10+1.878e-2./(t2.*1.0e+12-1.822e-2)+2.7359).*2.0)./lam1+(l.*pi.*sqrt(t3.*-1.354e+10+1.878e-2./(t3.*1.0e+12-1.822e-2)+2.7359).*2.0)./lam2;
end

end