function out1 = bboShift(lam1,lam2,lam3,theta,phi1,phi2,l)
%BBOSHIFT
%    OUT1 = BBOSHIFT(LAM1,LAM2,LAM3,THETA,PHI1,PHI2,L)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    05-Nov-2019 17:02:26

t2 = lam1.^2;
t3 = lam2.^2;
t6 = (theta.*pi)./1.8e2;
t4 = cos(t6);
t5 = lam3.^2;
t7 = sin(t6);
t8 = t5.*1.0e12;
out1 = l.*phi1+l.*phi2-(l.*pi.*sqrt(1.0./(t4.^2./(t5.*-1.354e10+1.878e-2./(t8-1.822e-2)+2.7359)+t7.^2./(t5.*-1.516e10+1.224e-2./(t8-1.667e-2)+2.3753))).*2.0)./lam3+(l.*pi.*sqrt(t2.*-1.354e10+1.878e-2./(t2.*1.0e12-1.822e-2)+2.7359).*2.0)./lam1+(l.*pi.*sqrt(t3.*-1.354e10+1.878e-2./(t3.*1.0e12-1.822e-2)+2.7359).*2.0)./lam2;
